### Required Libraries

In [30]:
import pandas as pd
import matplotlib.pyplot as plt
import html
from sklearn.metrics.pairwise import cosine_similarity

### The Dataset

In [31]:
path = './Datasets/'
booksDf = pd.read_csv(path+'Books.csv')
booksDf.info()

C:\Users\Admin\AppData\Local\Temp\ipykernel_408\2556762172.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  booksDf = pd.read_csv(path+'Books.csv')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271360 non-null  object
 1   Book-Title           271360 non-null  object
 2   Book-Author          271358 non-null  object
 3   Year-Of-Publication  271360 non-null  object
 4   Publisher            271358 non-null  object
 5   Image-URL-S          271360 non-null  object
 6   Image-URL-M          271360 non-null  object
 7   Image-URL-L          271357 non-null  object
dtypes: object(8)
memory usage: 16.6+ MB

In [32]:
ratingsDf =  pd.read_csv(path+'Ratings.csv')
ratingsDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1149780 entries, 0 to 1149779
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   User-ID      1149780 non-null  int64
 1   ISBN         1149780 non-null  object
 2   Book-Rating  1149780 non-null  int64
dtypes: int64(2), object(1)
memory usage: 26.3+ MB

In [59]:
ratingsDf["User-ID"].nunique()

105283

In [33]:
usersDf = pd.read_csv(path+'Users.csv')
usersDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278858 entries, 0 to 278857
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   User-ID   278858 non-null  int64
 1   Location  278858 non-null  object
 2   Age       168096 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 6.4+ MB

### Checking for the missing observations

In [34]:
for col in booksDf.columns:
    print(f"{col} : {booksDf[col].isnull().sum()} missing values")

ISBN : 0 missing values
Book-Title : 0 missing values
Book-Author : 2 missing values
Year-Of-Publication : 0 missing values
Publisher : 2 missing values
Image-URL-S : 0 missing values
Image-URL-M : 0 missing values
Image-URL-L : 3 missing values

In [35]:
for col in ratingsDf.columns:
    print(f"{col} : {ratingsDf[col].isnull().sum()} missing values")

User-ID : 0 missing values
ISBN : 0 missing values
Book-Rating : 0 missing values

### Preprocess the Datasets

In [36]:
booksDf = pd.read_csv('./Datasets/Books.csv')

C:\Users\Admin\AppData\Local\Temp\ipykernel_408\3645725999.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  booksDf = pd.read_csv('./Datasets/Books.csv')

In [37]:
# removing the missing values 
booksDf = booksDf.dropna(axis=0)

for col in booksDf.columns:
    print(f"{col} : {booksDf[col].isnull().sum()} missing values")

ISBN : 0 missing values
Book-Title : 0 missing values
Book-Author : 0 missing values
Year-Of-Publication : 0 missing values
Publisher : 0 missing values
Image-URL-S : 0 missing values
Image-URL-M : 0 missing values
Image-URL-L : 0 missing values

In [38]:
# removing duplicated books, ie. books having same book title but different ISBN
booksDf = booksDf.groupby('Book-Title').first().reset_index()
booksDf

,Book-Title,ISBN,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,A Light in the Storm: The Civil War Diary of ...,0590567330,Karen Hesse,1999,Hyperion Books for Children,http://images.amazon.com/images/P/0590567330.0...,http://images.amazon.com/images/P/0590567330.0...,http://images.amazon.com/images/P/0590567330.0...
1,Always Have Popsicles,0964147726,Rebecca Harvin,1994,Rebecca L. Harvin,http://images.amazon.com/images/P/0964147726.0...,http://images.amazon.com/images/P/0964147726.0...,http://images.amazon.com/images/P/0964147726.0...
2,Apple Magic (The Collector's series),0942320093,Martina Boudreau,1984,Amer Cooking Guild,http://images.amazon.com/images/P/0942320093.0...,http://images.amazon.com/images/P/0942320093.0...,http://images.amazon.com/images/P/0942320093.0...
3,"Ask Lily (Young Women of Faith: Lily Series, ...",0310232546,Nancy N. Rue,2001,Zonderkidz,http://images.amazon.com/images/P/0310232546.0...,http://images.amazon.com/images/P/0310232546.0...,http://images.amazon.com/images/P/0310232546.0...
4,Beyond IBM: Leadership Marketing and Finance ...,0962295701,Lou Mobley,1989,"Teleonet, Incorporated",http://images.amazon.com/images/P/0962295701.0...,http://images.amazon.com/images/P/0962295701.0...,http://images.amazon.com/images/P/0962295701.0...
...,...,...,...,...,...,...,...,...
242124,Ã?Â?lpiraten.,3499232499,Janwillem van de Wetering,2002,Rowohlt Tb.,http://images.amazon.com/images/P/3499232499.0...,http://images.amazon.com/images/P/3499232499.0...,http://images.amazon.com/images/P/3499232499.0...
242125,Ã?Â?rger mit Produkt X. Roman.,325721538X,Joan Aiken,1987,Diogenes Verlag,http://images.amazon.com/images/P/325721538X.0...,http://images.amazon.com/images/P/325721538X.0...,http://images.amazon.com/images/P/325721538X.0...
242126,Ã?Â?sterlich leben.,3451274973,Anselm GrÃ?Â¼n,2001,"Herder, Freiburg",http://images.amazon.com/images/P/3451274973.0...,http://images.amazon.com/images/P/3451274973.0...,http://images.amazon.com/images/P/3451274973.0...
242127,Ã?Â?stlich der Berge.,3442725739,David Guterson,2000,btb,http://images.amazon.com/images/P/3442725739.0...,http://images.amazon.com/images/P/3442725739.0...,http://images.amazon.com/images/P/3442725739.0...
242128,Ã?Â?thique en toc,2842192508,Didier Daeninckx,1998,Baleine,http://images.amazon.com/images/P/2842192508.0...,http://images.amazon.com/images/P/2842192508.0...,http://images.amazon.com/images/P/2842192508.0...

In [39]:
# removing html character entities like '&amp;'
booksDf['Book-Title'] = booksDf['Book-Title'].apply(lambda x: html.unescape(x))
booksDf['Publisher'] = booksDf['Publisher'].apply(lambda x: html.unescape(x))

In [40]:
# saving the preprocessed data frame
booksDf.to_csv('./Datasets/preProcessedBooksDf.csv', index=False)

### Popularity Based Recommendation

In [41]:
ratingsDf = pd.read_csv('./Datasets/Ratings.csv')
booksDf = pd.read_csv('./Datasets/preProcessedBooksDf.csv')

In [42]:
booksDf.nunique()

# no duplicated books are there

Book-Title             242129
ISBN                   242129
Book-Author             99682
Year-Of-Publication       112
Publisher               16457
Image-URL-S            242128
Image-URL-M            242128
Image-URL-L            242128
dtype: int64

In [43]:
# m = minimum number of votes required to be listed in the popularity list
m = 100

# C = average ratings across all over the report 
C = ratingsDf["Book-Rating"].mean()

# selected books
vote_count = ratingsDf["ISBN"].value_counts()
selected_books = list(vote_count[vote_count>=m].index)

# votes per books
v = ratingsDf.loc[ratingsDf["ISBN"].isin(selected_books)]["ISBN"].value_counts()

# average ratings of the selected books
R = ratingsDf.loc[ratingsDf["ISBN"].isin(selected_books)].groupby("ISBN")["Book-Rating"].mean().reindex(selected_books)

# popularity = (vR + mC)/(v+m)
popularity_score = ((v*R+m*C)/(v+m)).reindex(selected_books).reset_index()
popularity_score.columns = ["ISBN", "popularity"]
popularity_score

           ISBN  popularity
0    0971880107    1.090582
1    0316666343    4.353903
2    0385504209    4.470697
3    0060928336    3.378239
4    0312195516    4.156373
..          ...         ...
726  0786866586    2.903475
727  0449203794    2.723475
728  0425151867    2.898475
729  0312966806    2.413475
730  0425136981    2.583475

[731 rows x 2 columns]

In [44]:
# merging the average ratings with the popularity dataset
avg_ratings = R.reset_index()
avg_ratings.columns = ["ISBN", "avg_ratings"]
popularity_score = pd.merge(popularity_score, avg_ratings, on="ISBN")

# merging thenumber of votes with the popularity dataset
n_votes = v.reset_index()
n_votes.columns = ["ISBN", "nvotes"]
popularity_score = pd.merge(popularity_score, n_votes, on="ISBN")

popularity_score

           ISBN  popularity  avg_ratings  nvotes
0    0971880107    1.090582     1.019584    2502
1    0316666343    4.353903     4.468726    1295
2    0385504209    4.470697     4.652322     883
3    0060928336    3.378239     3.448087     732
4    0312195516    4.156373     4.334716     723
..          ...         ...          ...     ...
726  0786866586    2.903475     2.940000     100
727  0449203794    2.723475     2.580000     100
728  0425151867    2.898475     2.930000     100
729  0312966806    2.413475     1.960000     100
730  0425136981    2.583475     2.300000     100

[731 rows x 4 columns]

In [45]:
# books information according to the descending order of the popularity score
popularBooks = pd.merge(popularity_score, booksDf, on="ISBN").sort_values('popularity', ascending=False).reset_index()
popularBooks = popularBooks.drop("index", axis=1)
popularBooks['avg_ratings'] = popularBooks['avg_ratings'].map(lambda x: round(x, 2))
popularBooks.head()

,ISBN,popularity,avg_ratings,nvotes,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0439139597,5.291480,6.54,194,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...
1,0439136350,5.254865,6.47,197,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,1999,Scholastic,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...
2,0590353403,5.058564,6.36,168,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,1998,Scholastic,http://images.amazon.com/images/P/0590353403.0...,http://images.amazon.com/images/P/0590353403.0...,http://images.amazon.com/images/P/0590353403.0...
3,043935806X,4.948606,5.57,334,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,2003,Scholastic,http://images.amazon.com/images/P/043935806X.0...,http://images.amazon.com/images/P/043935806X.0...,http://images.amazon.com/images/P/043935806X.0...
4,059035342X,4.597161,4.90,571,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,1999,Arthur A. Levine Books,http://images.amazon.com/images/P/059035342X.0...,http://images.amazon.com/images/P/059035342X.0...,http://images.amazon.com/images/P/059035342X.0...

In [46]:
popularBooks.shape

(594, 11)

In [47]:
# saving the popularity df
popularBooks.to_csv('./Datasets/popularBooks.csv', index=False)

### Collaborative Filtering Based Recommendation

In [48]:
ratingsDf = pd.read_csv('./Datasets/Ratings.csv')
booksDf = pd.read_csv('./Datasets/preProcessedBooksDf.csv')

In [49]:
# merging the ratings and books to get a new dataframe
df = pd.merge(ratingsDf, booksDf, on="ISBN")
df

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
883067,276688,0425150526,0,Death Crosses the Border,Janice Steinberg,1995,Berkley Publishing Group,http://images.amazon.com/images/P/0425150526.0...,http://images.amazon.com/images/P/0425150526.0...,http://images.amazon.com/images/P/0425150526.0...
883068,276688,0449907422,0,Jazz Funeral: A Skip Langdon Novel,Julie Smith,1993,Ballantine Books,http://images.amazon.com/images/P/0449907422.0...,http://images.amazon.com/images/P/0449907422.0...,http://images.amazon.com/images/P/0449907422.0...
883069,276690,0590907301,0,Triplet Trouble and the Class Trip (Triplet Tr...,Debbie Dadey,1997,Apple,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...
883070,276704,0679752714,0,A Desert of Pure Feeling (Vintage Contemporaries),Judith Freeman,1997,Vintage Books USA,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...
883071,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...

In [50]:
# getting the book titles that has atleast 100 votes
vote_count = df[['Book-Title', 'User-ID']].value_counts().groupby('Book-Title').sum()
freq_read_books = list(vote_count[vote_count>=100].index)
freq_read_books

['1984',
 '1st to Die: A Novel',
 '2nd Chance',
 '4 Blondes',
 'A Beautiful Mind: The Life of Mathematical Genius and Nobel Laureate John Nash',
 'A Case of Need',
 'A Child Called \\It\\": One Child\'s Courage to Survive"',
 'A Civil Action',
 'A Confederacy of Dunces (Evergreen Book)',
 'A Fine Balance',
 'A Girl Named Zippy: Growing Up Small in Mooreland Indiana (Today Show Book Club #3)',
 'A Heartbreaking Work of Staggering Genius',
 'A Is for Alibi (Kinsey Millhone Mysteries (Paperback))',
 'A Lesson Before Dying (Vintage Contemporaries (Paperback))',
 'A Light in the Window (The Mitford Years)',
 'A Painted House',
 'A Patchwork Planet',
 'A Prayer for Owen Meany',
 'A Thin Dark Line (Mysteries & Horror)',
 "A Thousand Acres (Ballantine Reader's Circle)",
 'A Time to Kill',
 "A Virtuous Woman (Oprah's Book Club (Paperback))",
 'A Walk in the Woods: Rediscovering America on the Appalachian Trail (Official Guides to the Appalachian Trail)',
 'A Walk to Remember',
 'A Widow for One Year',
 'A Wrinkle In Time',
 'A Wrinkle in Time',
 'A Year in Provence',
 "ANGELA'S ASHES",
 'About a Boy',
 'About a Boy (Movie Tie-In)',
 'Acceptable Risk',
 'Airframe',
 'All Around the Town',
 'All I Really Need to Know',
 'All That Remains (Kay Scarpetta Mysteries (Paperback))',
 'All the Pretty Horses (The Border Trilogy, Vol 1)',
 'Along Came a Spider (Alex Cross Novels)',
 'American Gods',
 'American Psycho (Vintage Contemporaries)',
 "Angela's Ashes (MMP) : A Memoir",
 "Angela's Ashes: A Memoir",
 'Angels & Demons',
 'Angus, Thongs and Full-Frontal Snogging: Confessions of Georgia Nicolson',
 'Animal Dreams',
 'Animal Farm',
 'Anne Frank: The Diary of a Young Girl',
 'Anne of Avonlea (Anne of Green Gables Novels (Paperback))',
 'Anne of Green Gables (Anne of Green Gables Novels (Paperback))',
 'Artemis Fowl (Artemis Fowl, Book 1)',
 'Ashes to Ashes',
 'At Home in Mitford (The Mitford Years)',
 'Atlantis Found',
 'Atlas Shrugged',
 'Atonement : A Novel',
 'Atonement: A Novel',
 'B Is for Burglar (Kinsey Millhone Mysteries (Paperback))',
 'Back Roads',
 "Back When We Were Grownups : A Novel (Ballantine Reader's Circle)",
 'Bag of Bones',
 'Balzac and the Little Chinese Seamstress : A Novel',
 'Bastard Out of Carolina',
 'Beach House',
 'Bee Season: A Novel',
 'Before I Say Good-Bye',
 'Bel Canto: A Novel',
 'Beloved',
 'Beloved (Plume Contemporary Fiction)',
 "Big Cherry Holler: A Big Stone Gap Novel (Ballantine Reader's Circle)",
 "Big Stone Gap: A Novel (Ballantine Reader's Circle)",
 'Black Friday',
 'Black Notice',
 'Black and Blue',
 'Bleachers',
 'Blessings',
 'Blood Work',
 'Blow Fly: A Scarpetta Novel',
 'Body of Evidence (Kay Scarpetta Mysteries (Paperback))',
 'Body of Lies',
 'Breath, Eyes, Memory',
 'Breathing Lessons',
 'Bridget Jones : The Edge of Reason',
 "Bridget Jones's Diary",
 'Bridget Jones: The Edge of Reason',
 'C Is for Corpse (Kinsey Millhone Mysteries (Paperback))',
 "CAT'S EYE",
 'Call of the Wild',
 'Cane River',
 'Carolina Moon',
 'Cat & Mouse (Alex Cross Novels)',
 'Catch 22',
 'Catch Me If You Can: The True Story of a Real Fake',
 'Cause of Death',
 "Charlotte's Web (Trophy Newbery)",
 'Charming Billy',
 'Chicken Soup for the Soul (Chicken Soup for the Soul)',
 'Chicken Soup for the Teenage Soul (Chicken Soup for the Soul)',
 "Chicken Soup for the Woman's Soul (Chicken Soup for the Soul Series (Paper))",
 'Chocolat',
 'Chosen Prey',
 'Circle of Friends',
 'Clear and Present Danger (Jack Ryan Novels)',
 'Coast Road: A Novel',
 'Code to Zero',
 'Cold Mountain',
 'Cold Mountain : A Novel',
 'Confessions of a Shopaholic (Summer Display Opportunity)',
 'Confessions of an Ugly Stepsister : A Novel',
 'Congo',
 'Coraline',
 "Corelli's Mandolin : A Novel",
 'Cruel & Unusual (Kay Scarpetta Mysteries (Paperback))',
 'Cry Wolf',
 'D Is for Deadbeat (Kinsey Millhone Mysteries (Paperback))',
 "Daddy's Little Girl",
 'Daisy Fay and the Miracle Man',
 'Dance upon the Air (Three Sisters Island Trilogy)',
 'Dances With Wolves',
 'Dark Paradise',
 'Dark Rivers of the Heart',
 'Daughter of Fortune',
 "Daughter of Fortune : A Novel (Oprah's Book Club (Hardcover))",
 'Daughter of Fortune: A Novel',
 'Debt of Honor (Jack Ryan Novels)',
 'Deception Point',
 'Degree of Guilt',
 'Deja Dead',
 'Desperation',
 'Diary of a Mad Bride (Summer Display Opportunity)',
 'Digital Fortress : A Thriller',
 'Disclosure',
 'Divine Secrets of the Ya-Ya Sisterhood : A Novel',
 'Divine Secrets of the Ya-Ya Sisterhood: A Novel',
 'Dolores Claiborne',
 "Don't Stand Too Close to a Naked Man",
 "Don't Sweat the Small Stuff and It's All Small Stuff : Simple Ways to Keep the Little Things from Taking Over Your Life (Don't Sweat the Small Stuff Series)",
 'Dr. Death (Alex Delaware Novels (Paperback))',
 'Dragonfly in Amber',
 'Dreamcatcher',
 'Drowning Ruth',
 "Drowning Ruth (Oprah's Book Club)",
 "Dude, Where's My Country?",
 'Dune (Remembering Tomorrow)',
 'Dust to Dust',
 'Dying for Chocolate (Culinary Mysteries (Paperback))',
 'E Is for Evidence: A Kinsey Millhone Mystery (Kinsey Millhone Mysteries (Paperback))',
 "East of Eden (Oprah's Book Club)",
 'Eaters of the Dead',
 'Eats, Shoots & Leaves: The Zero Tolerance Approach to Punctuation',
 'Echoes',
 'Eleventh Hour: An FBI Thriller (FBI Thriller (Jove Paperback))',
 'Ellen Foster',
 'Empire Falls',
 'Engaging The Enemy',
 'Envy',
 "Everything's Eventual : 14 Dark Tales",
 'Executive Orders (Jack Ryan Novels)',
 'Eyes of the Dragon',
 'F Is for Fugitive (Kinsey Millhone Mysteries (Paperback))',
 'FORREST GUMP (Movie Tie in)',
 'Face the Fire (Three Sisters Island Trilogy)',
 'Faking It',
 'Fall On Your Knees (Oprah #45)',
 'Falling Angels',
 'False Memory',
 'Fast Food Nation: The Dark Side of the All-American Meal',
 'Fatal Voyage',
 'Fear Nothing',
 'Final Target',
 'Five Quarters of the Orange',
 'Forever... : A Novel of Good and Evil, Love and Hope',
 "Fortune's Rocks: A Novel",
 "Foucault's Pendulum",
 'Four Blind Mice',
 'Four Blondes',
 'Four Past Midnight',
 'Four To Score (A Stephanie Plum Novel)',
 'Fried Green Tomatoes at the Whistle Stop Cafe',
 "From Potter's Field",
 'From a Buick 8 : A Novel',
 'From the Corner of His Eye',
 "Full House (Janet Evanovich's Full Series)",
 "Full Tilt (Janet Evanovich's Full Series)",
 'G Is for Gumshoe (Kinsey Millhone Mysteries (Paperback))',
 'Gap Creek: The Story Of A Marriage',
 "Gerald's Game",
 'Girl with a Pearl Earring',
 'Girl, Interrupted',
 'Good Omens',
 'Good in Bed',
 'Guilty as Sin',
 'H Is for Homicide (Kinsey Millhone Mysteries (Paperback))',
 'Hannibal',
 'Hard Eight : A Stephanie Plum Novel (A Stephanie Plum Novel)',
 'Harry Potter and the Chamber of Secrets (Book 2)',
 'Harry Potter and the Goblet of Fire (Book 4)',
 'Harry Potter and the Order of the Phoenix (Book 5)',
 'Harry Potter and the Prisoner of Azkaban (Book 3)',
 "Harry Potter and the Sorcerer's Stone (Book 1)",
 "Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))",
 'Heart of the Sea (Irish Trilogy)',
 'Hearts In Atlantis',
 'Hearts in Atlantis',
 'Heaven and Earth (Three Sisters Island Trilogy)',
 'Hemlock Bay',
 'Here on Earth',
 'Hide & Seek',
 'Hideaway',
 'High Fidelity',
 'High Five (A Stephanie Plum Novel)',
 'Holes (Yearling Newbery)',
 'Hot Six : A Stephanie Plum Novel (A Stephanie Plum Novel)',
 'House of Sand and Fog',
 'How the Garcia Girls Lost Their Accents (Plume Contemporary Fiction)',
 'How to Be Good',
 'How to Make an American Quilt',
 'I Is for Innocent',
 'I Know This Much Is True',
 "I Know This Much Is True (Oprah's Book Club)",
 'I Know Why the Caged Bird Sings',
 "I'll Be Seeing You",
 'Icy Sparks',
 'Inner Harbor (Quinn Brothers (Paperback))',
 'Intensity',
 'Interpreter of Maladies',
 'Interview with the Vampire',
 'Into the Wild',
 'Invasion',
 'Irish Hearts',
 'Ishmael: An Adventure of the Mind and Spirit',
 'Isle of Dogs',
 'J Is for Judgment',
 'Jack & Jill (Alex Cross Novels)',
 'Jemima J: A Novel About Ugly Ducklings and Swans',
 'Jewel',
 "Jewel (Oprah's Book Club)",
 'Jewels of the Sun (Irish Trilogy)',
 'Jonathan Livingston Seagull',
 'Jurassic Park',
 'K Is for Killer (Kinsey Millhone Mysteries (Paperback))',
 'Key of Knowledge (Key Trilogy (Paperback))',
 'Key of Light (Key Trilogy (Paperback))',
 'Key of Valor (Roberts, Nora. Key Trilogy, 3.)',
 'Kiss the Girls',
 'L Is for Lawless',
 'Lake Wobegon days',
 "Lamb : The Gospel According to Biff, Christ's Childhood Pal",
 'Lasher: Lives of the Mayfair Witches (Lives of the Mayfair Witches)',
 "Left Behind: A Novel of the Earth's Last Days (Left Behind #1)",
 "Left Behind: A Novel of the Earth's Last Days (Left Behind No. 1)",
 'Let Me Call You Sweetheart',
 'Lies and the Lying Liars Who Tell Them: A Fair and Balanced Look at the Right',
 'Life of Pi',
 'Lightning',
 'Like Water for Chocolate : A Novel in Monthly Installments with Recipes, Romances, and Home Remedies',
 'Like Water for Chocolate: A Novel in Monthly Installments With Recipes, Romances and Home Remedies',
 'Like Water for Chocolate: A Novel in Monthly Installments, With Recipes, Romances, and Home Remedies',
 'Little Altars Everywhere: A Novel',
 'Long After Midnight',
 'Lord of the Flies',
 'Love in the Time of Cholera (Penguin Great Books of the 20th Century)',
 'Loves Music, Loves to Dance',
 'Lucky : A Memoir',
 'Lucky Man: A Memoir',
 'M Is for Malice',
 'Manhattan Hunt Club',
 'Me Talk Pretty One Day',
 'Memoirs of a Geisha Uk',
 'Men Are from Mars, Women Are from Venus: A Practical Guide for Improving Communication and Getting What You Want in Your Relationships',
 'Middlesex: A Novel',
 'Midnight in the Garden of Good and Evil',
 'Midnight in the Garden of Good and Evil: A Savannah Story',
 'Midwives: A Novel',
 'Misery',
 'Miss Julia Speaks Her Mind : A Novel',
 'Monster : A Novel (Alex Delaware Novels (Paperback))',
 'Montana Sky',
 'Moo',
 'Moonlight Becomes You',
 'Morality for Beautiful Girls (No.1 Ladies Detective Agency)',
 'Mortal Prey',
 'Mr. Murder',
 'Mrs Dalloway',
 'Mystic River',
 'N Is for Noose',
 'Naked',
 'Neuromancer (Remembering Tomorrow)',
 'Neverwhere',
 'Nickel and Dimed: On (Not) Getting By in America',
 'Nicolae: The Rise of Antichrist (Left Behind No. 3)',
 'Night',
 'Night Sins',
 'Nightmares & Dreamscapes',
 'Nights in Rodanthe',
 'Notes from a Small Island',
 'Of Mice and Men (Penguin Great Books of the 20th Century)',
 'On the Road',
 'On the Street Where You Live',
 'One Door Away from Heaven',
 'One for the Money (A Stephanie Plum Novel)',
 'One for the Money (Stephanie Plum Novels (Paperback))',
 'Open House',
 "Open House (Oprah's Book Club (Paperback))",
 'P Is for Peril',
 'P Is for Peril (Kinsey Millhone Mysteries (Hardcover))',
 'Patriot Games (Jack Ryan Novels)',
 'Pay It Forward',
 'Peace Like a River',
 'Plainsong (Vintage Contemporaries)',
 'Pleading Guilty',
 'Plum Island',
 'Point of Origin',
 'Politically Correct Bedtime Stories: Modern Tales for Our Life and Times',
 'Portrait of a Killer: Jack the Ripper -- Case Closed',
 'Portrait of a Killer: Jack the Ripper-- Case Closed (Berkley True Crime)',
 'Possession : A Romance',
 'Postmortem',
 'Presumed Innocent',
 "Pretend You Don't See Her",
 'Prey',
 'Prey: A Novel',
 'Prodigal Summer',
 'Prodigal Summer: A Novel',
 'Purity in Death',
 'Q Is for Quarry',
 'Red Dragon',
 'Red Storm Rising',
 'Remember Me',
 'Riptide',
 'Rising Sun',
 'Rising Tides',
 "River's End",
 'River, Cross My Heart',
 'Rose Madder',
 'Roses Are Red (Alex Cross Novels)',
 'Running with Scissors: A Memoir',
 'SHIPPING NEWS',
 'Sanctuary',
 'Saving Faith',
 'Scarlett : The Sequel to Margaret Mitchell\'s \\Gone With the Wind\\""',
 "Schindler's List",
 'Sea Glass: A Novel',
 'Sea Swept (Quinn Brothers (Paperback))',
 'Seabiscuit',
 'Seabiscuit: An American Legend',
 'Secret History',
 'See How They Run',
 'Seinlanguage',
 'September',
 'Seven Habits Of Highly Effective People',
 'Shadowfires',
 "She's Come Undone (Oprah's Book Club (Paperback))",
 "She's Come Undone (Oprah's Book Club)",
 'Shell Seekers',
 'Shopaholic Takes Manhattan (Summer Display Opportunity)',
 'Shopaholic Ties the Knot',
 'Shopgirl',
 'Shopgirl : A Novella',
 'Sick Puppy',
 'Siddhartha',
 'Silence of the Lambs',
 'Silent Night : A Christmas Suspense Story',
 'Simple Abundance:  A Daybook of Comfort and Joy',
 'Sisterhood of the Traveling Pants',
 'Skipping Christmas',
 "Slaughterhouse Five or the Children's Crusade: A Duty Dance With Death",
 'Sleepers',
 "Smilla's Sense of Snow",
 "Song of Solomon (Oprah's Book Club (Paperback))",
 "Songs in Ordinary Time (Oprah's Book Club (Paperback))",
 "Sophie's World: A Novel About the History of Philosophy",
 'Soul Harvest: The World Takes Sides (Left Behind No. 4)',
 'Space',
 'Sphere',
 'Standing in the Rainbow',
 'Still Waters',
 'Stranger in a Strange Land (Remembering Tomorrow)',
 'Stupid White Men ...and Other Sorry Excuses for the State of the Nation!',
 'Summer Pleasures',
 'Survival of the Fittest: An Alex Delaware Novel',
 "Suzanne's Diary for Nicholas",
 'Table For Two',
 'Tara Road',
 'Tears of the Giraffe (No.1 Ladies Detective Agency)',
 'Tears of the Moon (Irish Trilogy)',
 'Tell Me Lies (Tell Me Lies)',
 'Tell No One',
 'The Alienist',
 'The Amazing Adventures of Kavalier & Clay',
 'The Andromeda Strain',
 'The Angel of Darkness',
 'The Bachelor (Warner Books Contemporary Romance)',
 'The Bad Beginning (A Series of Unfortunate Events, Book 1)',
 'The Bad Place',
 'The Beach House',
 'The Bean Trees',
 'The Bear and the Dragon (Jack Ryan Novels)',
 'The Big Bad Wolf: A Novel',
 'The Blind Assassin',
 'The Blue Nowhere : A Novel',
 'The Body Farm',
 'The Bone Collector (Lincoln Rhyme Novels (Paperback))',
 "The Bonesetter's Daughter",
 'The Bonfire of the Vanities',
 "The Book of Ruth (Oprah's Book Club (Paperback))",
 'The Bourne Identity',
 'The Boy Next Door',
 'The Brethren',
 'The Bridges of Madison County',
 'The Burden of Proof',
 'The Cardinal of the Kremlin (Jack Ryan Novels)',
 'The Catcher in the Rye',
 'The Celestine Prophecy (Celestine Prophecy)',
 'The Chamber',
 "The Clan of the Cave Bear (Earth's Children (Paperback))",
 'The Client',
 'The Color Purple',
 'The Color of Magic',
 "The Color of Water: A Black Man's Tribute to His White Mother",
 'The Copper Beech',
 'The Corrections',
 'The Corrections: A Novel',
 'The Curious Incident of the Dog in the Night-Time (Today Show Book Club #13)',
 'The Da Vinci Code',
 'The Dark Half',
 "The Deep End of the Ocean (Oprah's Book Club (Hardcover))",
 'The Devil Wears Prada : A Novel',
 "The Dive From Clausen's Pier (Alex Awards)",
 "The Dive From Clausen's Pier : A Novel (Vintage Contemporaries (Paperback))",
 'The Divine Secrets of the Ya-Ya Sisterhood: A Novel',
 'The Dogs of Babel (Today Show Book Club #12)',
 'The Door to December',
 "The Dress Lodger (Ballantine Reader's Circle)",
 'The English Patient',
 'The Eye of the World (The Wheel of Time, Book 1)',
 'The Eyes of Darkness',
 'The Eyre Affair: A Novel',
 'The Face of Deception',
 'The Fellowship of the Ring (The Lord of the Rings, Part 1)',
 'The Five People You Meet in Heaven',
 'The Forgotten (Peter Decker & Rina Lazarus Novels (Paperback))',
 'The Four Agreements: A Practical Guide to Personal Freedom',
 'The Genesis Code',
 'The Girl Who Loved Tom Gordon',
 'The Girl Who Loved Tom Gordon : A Novel',
 "The Girls' Guide to Hunting and Fishing",
 'The Giver (21st Century Reference)',
 'The Glass Lake',
 'The God of Small Things',
 "The Handmaid's Tale",
 "The Handmaid's Tale : A Novel",
 'The Hobbit : The Enchanting Prelude to The Lord of the Rings',
 'The Horse Whisperer',
 'The Hot Zone',
 'The Hours : A Novel',
 'The Hours: A Novel',
 'The House of Thunder',
 'The House of the Spirits',
 'The House on Mango Street (Vintage Contemporaries)',
 "The Idiot Girls' Action Adventure Club",
 'The Jester',
 'The Joy Luck Club',
 'The Key to Midnight',
 'The Killer Angels',
 'The Killing Game: Only One Can Win...and the Loser Dies',
 'The King of Torts',
 'The Last Juror',
 'The Last Precinct',
 'The Last Time They Met : A Novel',
 "The Liar's Club: A Memoir",
 'The Loop',
 "The Lost Boy: A Foster Child's Search for the Love of a Family",
 'The Lost World',
 'The Lottery Winner : Alvirah And Willy Stories',
 'The Lovely Bones: A Novel',
 'The Mists of Avalon',
 'The Mulberry Tree',
 'The Mummy or Ramses the Damned',
 'The Murder Book',
 'The Nanny Diaries: A Novel',
 'The Next Accident',
 "The No. 1 Ladies' Detective Agency",
 "The No. 1 Ladies' Detective Agency (Today Show Book Club #8)",
 'The Notebook',
 'The Other Boleyn Girl',
 'The Partner',
 'The Pelican Brief',
 'The Perfect Husband',
 'The Perks of Being a Wallflower',
 'The Phantom Tollbooth',
 'The Pillars of the Earth',
 "The Pilot's Wife",
 "The Pilot's Wife : A Novel",
 "The Pilot's Wife : A Novel Tag: Author of the Weight of Water (Oprah's Book Club (Hardcover))",
 "The Plains of Passage (Earth's Children (Paperback))",
 'The Poisonwood Bible',
 'The Poisonwood Bible: A Novel',
 'The Prince of Tides',
 "The Princess Bride: S Morgenstern's Classic Tale of True Love and High Adventure",
 'The Princess Diaries',
 'The Professor and the Madman: A Tale of Murder, Insanity, and the Making of The Oxford English Dictionary',
 'The Queen of the Damned (Vampire Chronicles (Paperback))',
 'The Rainmaker',
 'The Rapture of Canaan',
 'The Red Tent (Bestselling Backlist)',
 'The Reef',
 'The Remains of the Day (Vintage International)',
 'The Reptile Room (A Series of Unfortunate Events, Book 2)',
 'The Rescue',
 'The Return Journey',
 'The Return of the King (The Lord of the Rings, Part 3)',
 'The Runaway Jury',
 "The Samurai's Garden : A Novel",
 'The Saving Graces: A Novel',
 'The Secret Life of Bees',
 "The Shelters of Stone (Earth's Children Series, No 5)",
 'The Shipping News : A Novel',
 'The Sigma Protocol',
 'The Simple Truth',
 'The Sparrow',
 'The Stand: Complete and Uncut',
 'The Stone Diaries',
 'The Stone Monkey (Lincoln Rhyme Novels (Paperback))',
 'The Street Lawyer',
 'The Sum of All Fears',
 'The Sum of All Fears (Jack Ryan Novels)',
 'The Summerhouse',
 'The Summons',
 'The Surgeon',
 "The Sweet Potato Queens' Book of Love",
 'The Tale of the Body Thief (Vampire Chronicles (Paperback))',
 'The Tao of Pooh',
 'The Temple of My Familiar',
 'The Testament',
 'The Third Twin',
 'The Thorn Birds',
 'The Tommyknockers',
 'The Two Towers (The Lord of the Rings, Part 2)',
 'The Ugly Duckling',
 'The Valley of Horses',
 'The Vampire Lestat (Vampire Chronicles, Book II)',
 'The Virgin Blue',
 'The Virgin Suicides',
 'The Weight of Water',
 'The Weight of Water : A Novel Tag: Author of Resistance and Strange Fits of Passion',
 'The Winner',
 'The Witching Hour (Lives of the Mayfair Witches)',
 'The Woman Next Door',
 'The World According to Garp',
 'Their Eyes Were Watching God: A Novel',
 'Thousand Acres',
 'Three Fates',
 'Three Junes',
 'Three To Get Deadly : A Stephanie Plum Novel (A Stephanie Plum Novel)',
 'Timeline',
 'Tis : A Memoir',
 'To Kill a Mockingbird',
 'To the Nines: A Stephanie Plum Novel',
 "Tom Clancy's Op-Center (Tom Clancy's Op Center (Paperback))",
 "Tom Clancy's Op-Center: Mirror Image (Tom Clancy's Op Center (Paperback))",
 'Total Control',
 'Tribulation Force: The Continuing Drama of Those Left Behind (Left Behind No. 2)',
 'Truly, Madly Manhattan',
 "Tuesdays with Morrie: An Old Man, a Young Man, and Life's Greatest Lesson",
 'Two for the Dough',
 'Under the Tuscan Sun',
 'Unspeakable',
 'Valhalla Rising (Dirk Pitt Adventures (Paperback))',
 "Vinegar Hill (Oprah's Book Club (Paperback))",
 'Violets Are Blue',
 'Waiting (Vintage International)',
 'We Were the Mulvaneys',
 "We'll Meet Again",
 'Welcome to Temptation',
 'Welcome to the World, Baby Girl!',
 'What Looks Like Crazy On An Ordinary Day',
 "What to Expect When You're Expecting (Revised Edition)",
 "Where the Heart Is (Oprah's Book Club (Paperback))",
 'Where the Red Fern Grows',
 'While I Was Gone',
 'While My Pretty One Sleeps',

In [51]:
len(freq_read_books)

594

In [52]:
# getting the users who has rated atleast 100 books
book_rated_by_users = df[['Book-Title', 'User-ID']].value_counts().groupby('User-ID').sum()
user_rated_many_books = list(book_rated_by_users[book_rated_by_users>=100].index)
user_rated_many_books

[254,
 507,
 882,
 1424,
 1435,
 1733,
 1903,
 2033,
 2110,
 2276,
 2358,
 2766,
 2891,
 2977,
 3363,
 3371,
 3757,
 3827,
 4017,
 4385,
 5582,
 5903,
 6242,
 6251,
 6323,
 6543,
 6563,
 6575,
 7125,
 7158,
 7286,
 7346,
 7915,
 8066,
 8067,
 8245,
 8253,
 8284,
 8362,
 8681,
 8782,
 8890,
 8936,
 8971,
 9141,
 9417,
 9747,
 9856,
 9908,
 10314,
 10354,
 10447,
 10819,
 11601,
 11629,
 11676,
 11724,
 11993,
 12538,
 12824,
 12835,
 12982,
 13082,
 13093,
 13273,
 13552,
 13582,
 13850,
 14079,
 14232,
 14387,
 14422,
 14456,
 14521,
 14638,
 15408,
 15418,
 15957,
 16106,
 16155,
 16488,
 16634,
 16795,
 16916,
 16943,
 16966,
 17190,
 17282,
 17859,
 17950,
 18067,
 18082,
 18172,
 18401,
 19085,
 19664,
 19711,
 19842,
 20060,
 20115,
 20201,
 21014,
 21252,
 21364,
 21576,
 21659,
 22625,
 23288,
 23571,
 23768,
 23872,
 23902,
 24194,
 24539,
 24921,
 25131,
 25409,
 25436,
 25601,
 25981,
 26084,
 26516,
 26535,
 26544,
 26583,
 26593,
 26883,
 27140,
 27169,
 27462,
 27472,
 27617,
 27647,
 27788,
 27812,
 28204,
 28360,
 28523,
 28591,
 28634,
 28666,
 28938,
 29259,
 29526,
 29855,
 29915,
 30072,
 30273,
 30276,
 30487,
 30509,
 30511,
 30533,
 30711,
 30716,
 30735,
 30810,
 30824,
 30972,
 31040,
 31308,
 31315,
 31391,
 31466,
 31556,
 31611,
 31826,
 31846,
 31919,
 32122,
 32195,
 32440,
 32627,
 32721,
 32773,
 33145,
 33580,
 33974,
 34300,
 35050,
 35407,
 35433,
 35836,
 35857,
 35859,
 36256,
 36299,
 36327,
 36554,
 36606,
 36609,
 36715,
 36836,
 36907,
 37208,
 37538,
 37567,
 37644,
 37712,
 37950,
 38023,
 38273,
 38281,
 38464,
 38556,
 38781,
 39281,
 39467,
 39502,
 39616,
 39646,
 39773,
 40012,
 40889,
 40943,
 41084,
 41227,
 41700,
 41781,
 41841,
 42093,
 42914,
 43246,
 43619,
 43806,
 43842,
 43910,
 44296,
 44595,
 44728,
 44845,
 44893,
 45557,
 46351,
 46398,
 46443,
 46909,
 47316,
 47971,
 48025,
 48046,
 48355,
 48494,
 49109,
 49144,
 49422,
 49460,
 49889,
 50225,
 50547,
 50730,
 51094,
 51350,
 51386,
 51450,
 51526,
 51742,
 51883,
 52199,
 52203,
 52350,
 52584,
 52614,
 52853,
 52917,
 53174,
 53220,
 53392,
 53456,
 53628,
 53729,
 54218,
 54898,
 55075,
 55178,
 55187,
 55490,
 55492,
 55493,
 55548,
 55734,
 55858,
 55892,
 55927,
 56039,
 56271,
 56360,
 56399,
 56447,
 56554,
 56856,
 56959,
 57006,
 57108,
 58363,
 58911,
 59150,
 59172,
 59189,
 59269,
 59390,
 59727,
 59971,
 60098,
 60244,
 60277,
 60319,
 60337,
 60569,
 60707,
 60858,
 61028,
 61147,
 61619,
 61901,
 62272,
 62755,
 62862,
 62881,
 62891,
 62895,
 63394,
 63714,
 63938,
 63956,
 64241,
 64436,
 64440,
 65258,
 66680,
 66942,
 67403,
 67547,
 67663,
 67840,
 68185,
 68555,
 69042,
 69078,
 69232,
 69355,
 69378,
 69405,
 69697,
 69721,
 69808,
 69971,
 70052,
 70065,
 70415,
 70594,
 71470,
 71568,
 71712,
 71739,
 72352,
 72992,
 73196,
 73394,
 73651,
 73681,
 73923,
 75081,
 75115,
 75591,
 75595,
 75860,
 76151,
 76223,
 76352,
 76482,
 76483,
 76499,
 76626,
 76818,
 76942,
 77383,
 77480,
 77809,
 77940,
 78448,
 78553,
 78783,
 78834,
 78973,
 79186,
 79441,
 79942,
 80538,
 80555,
 80683,
 80810,
 81045,
 81207,
 81368,
 81492,
 81560,
 81609,
 81848,
 81977,
 82407,
 82511,
 82831,
 82893,
 82926,
 83109,
 83287,
 83637,
 83671,
 84024,
 85426,
 85526,
 85656,
 85701,
 85757,
 85993,
 86145,
 86189,
 86202,
 86243,
 86641,
 86835,
 86947,
 87141,
 87143,
 87555,
 87712,
 87746,
 87974,
 88122,
 88283,
 88677,
 88693,
 88733,
 88793,
 88937,
 89014,
 89307,
 89602,
 89891,
 90232,
 91113,
 91203,
 91266,
 91342,
 91832,
 91931,
 92547,
 92652,
 92810,
 92853,
 92861,
 92979,
 93047,
 93085,
 93092,
 93147,
 93363,
 93426,
 93629,
 94242,
 94347,
 94853,
 94923,
 94951,
 94985,
 95010,
 95193,
 95316,
 95359,
 95902,
 95903,
 95923,
 95932,
 95991,
 96054,
 96448,
 96771,
 97160,
 97754,
 97874,
 98297,
 98391,
 98686,
 98741,
 98758,
 98787,
 98904,
 99955,
 100459,
 100578,
 100644,
 100846,
 100906,
 101209,
 101305,
 101606,
 101851,
 101876,
 102275,
 102359,
 102647,
 102702,
 102967,
 103304,
 104058,
 104113,
 104399,
 104429,
 104636,
 104665,
 105028,
 105054,
 105108,
 105374,
 105517,
 105937,
 105979,
 106007,
 106225,
 106816,
 106936,
 106988,
 107021,
 107244,
 107301,
 107453,
 107784,
 107951,
 108005,
 108285,
 108352,
 108405,
 108752,
 108773,
 108799,
 109461,
 109574,
 109901,
 109955,
 110029,
 110076,
 110214,
 110267,
 110373,
 110483,
 110912,
 110934,
 110973,
 111174,
 111578,
 111847,
 111947,
 112001,
 112026,
 112083,
 112541,
 112881,
 113270,
 113467,
 113519,
 113817,
 113904,
 113955,
 113983,
 114178,
 114216,
 114368,
 114414,
 114444,
 114544,
 114865,
 114868,
 114988,
 115002,
 115003,
 115120,
 115234,
 115435,
 115490,
 116122,
 116599,
 117111,
 117251,
 117384,
 117539,
 117594,
 118434,
 119248,
 119575,
 119749,
 119858,
 120090,
 120093,
 120548,
 120565,
 120598,
 120908,
 121251,
 122429,
 122793,
 122881,
 123056,
 123094,
 123095,
 123460,
 123608,
 123625,
 123790,
 123883,
 123981,
 124078,
 124079,
 124310,
 124363,
 124487,
 124489,
 124597,
 124942,
 125039,
 125203,
 125287,
 125411,
 125519,
 125692,
 125774,
 126492,
 126604,
 126693,
 126736,
 127129,
 127200,
 127233,
 127359,
 127429,
 127826,
 127914,
 128085,
 128208,
 128696,
 128835,
 129008,
 129074,
 129084,
 129358,
 129465,
 129503,
 129563,
 129716,
 129851,
 130438,
 130474,
 130554,
 130570,
 130571,
 131027,
 131046,
 131126,
 131402,
 131837,
 131855,
 132083,
 132173,
 132492,
 132663,
 132836,
 133296,
 133571,
 133689,
 133747,
 133868,
 134247,
 134434,
 134797,
 134837,
 134869,
 135045,
 135149,
 135265,
 135458,
 135831,
 136010,
 136139,
 136205,
 136252,
 136348,
 136382,
 136473,
 136509,
 137397,
 137589,
 137688,
 138073,
 138097,
 138198,
 138441,
 138543,
 138578,
 138602,
 138844,
 138883,
 138995,
 139141,
 139467,
 139742,
 140000,
 140036,
 140358,
 141444,
 141491,
 141493,
 141710,
 141819,
 141901,
 141902,
 142093,
 142121,
 142256,
 142454,
 142524,
 143163,
 143175,
 143211,
 143253,
 143415,
 143792,
 143968,
 144194,
 144255,
 144531,
 144555,
 145165,
 145431,
 145449,
 145451,
 145619,
 145641,
 146113,
 146175,
 146230,
 146348,
 146564,
 146803,
 147141,
 147166,
 147224,
 147451,
 147686,
 147847,
 147965,
 148199,
 148258,
 148744,
 148798,
 148966,
 149069,
 149084,
 149690,
 149907,
 149908,
 149934,
 150124,
 150498,
 150561,
 150896,
 150968,
 150979,
 151098,
 151107,
 151503,
 151589,
 151702,
 151790,
 151806,
 152186,
 152249,
 152354,
 152514,
 153054,
 153563,
 153662,
 153718,
 154070,
 154346,
 154992,
 155014,
 155147,
 155219,
 155463,
 155495,
 155916,
 156150,
 156214,
 156269,
 156300,
 156467,
 157247,
 157273,
 157799,
 157811,
 158226,
 158254,
 158295,
 159033,
 159376,
 159440,
 159858,
 160032,
 160295,
 160401,
 160558,
 160681,
 160819,
 161037,
 161041,
 161348,
 161752,
 161974,
 162052,
 162155,
 162590,
 162639,
 162738,
 163202,
 163319,
 163433,
 163570,
 163759,
 163761,
 163804,
 163973,
 164027,
 164096,
 164323,
 164465,
 164533,
 164675,
 164828,
 164905,
 165232,
 165308,
 165319,
 165759,
 166123,
 166596,
 166824,
 167349,
 167471,
 167800,
 168036,
 168047,
 168064,
 168144,
 168245,
 168387,
 168464,
 169233,
 169663,
 169682,
 169699,
 169779,
 170184,
 170229,
 170415,
 170513,
 170518,
 170575,
 170595,
 170634,
 170742,
 170947,
 171078,
 171118,
 171970,
 172030,
 172061,
 172512,
 172742,
 172760,
 172888,
 173018,
 173291,
 173415,
 173481,
 173632,
 173679,
 173684,
 173835,
 174092,
 174216,
 174304,
 174326,
 174791,
 174830,
 174848,
 174892,
 175003,
 175052,
 175329,
 175886,
 176667,
 177072,
 177090,
 177180,
 177374,
 177432,
 177458,
 177690,
 178130,
 178181,
 178199,
 178240,
 178522,
 178667,
 178950,
 179718,
 179730,
 179733,
 179744,
 179772,
 179978,
 180032,
 180348,
 180378,
 180586,
 180651,
 180917,
 180957,
 181076,
 181176,
 181687,
 182053,
 182085,
 182086,
 182334,
 182414,
 182442,
 182746,
 182987,
 182993,
 183046,
 183088,
 183187,
 183196,
 183287,
 183340,
 183958,
 183995,
 184299,
 184513,
 184532,
 185176,
 185233,
 185384,
 185771,
 186039,
 186547,
 186570,
 187065,
 187145,
 187170,
 187256,
 187517,
 187520,
 187763,
 188010,
 188951,
 189080,
 189139,
 189334,
 189516,
 189835,
 189973,
 190459,
 190708,
 190741,
 190807,
 190925,
 191187,
 192093,
 192176,
 193458,
 193499,
 193560,
 193898,
 194600,
 194669,
 194676,
 195469,
 195694,
 196018,
 196047,
 196077,
 196106,
 196108,
 196160,
 196457,
 196466,
 196502,
 196738,
 ...]

In [53]:
len(user_rated_many_books)

1433

In [54]:
# filtering the merged data to the seleted users
df = df.loc[df["User-ID"].isin(user_rated_many_books),]

# filtering the merged data to the selected books
df = df.loc[df["Book-Title"].isin(freq_read_books),].reset_index().drop('index', axis=1)
df

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,277427,0425115801,0,Lightning,Dean R. Koontz,1996,Berkley Publishing Group,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...
1,9856,0425115801,7,Lightning,Dean R. Koontz,1996,Berkley Publishing Group,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...
2,13552,0425115801,10,Lightning,Dean R. Koontz,1996,Berkley Publishing Group,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...
3,14521,0425115801,0,Lightning,Dean R. Koontz,1996,Berkley Publishing Group,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...
4,16795,0425115801,8,Lightning,Dean R. Koontz,1996,Berkley Publishing Group,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...
...,...,...,...,...,...,...,...,...,...,...
49695,247055,0515135739,7,Eleventh Hour: An FBI Thriller (FBI Thriller (...,Catherine Coulter,2004,Jove Books,http://images.amazon.com/images/P/0515135739.0...,http://images.amazon.com/images/P/0515135739.0...,http://images.amazon.com/images/P/0515135739.0...
49696,251613,0515135739,0,Eleventh Hour: An FBI Thriller (FBI Thriller (...,Catherine Coulter,2004,Jove Books,http://images.amazon.com/images/P/0515135739.0...,http://images.amazon.com/images/P/0515135739.0...,http://images.amazon.com/images/P/0515135739.0...
49697,252071,0515135739,0,Eleventh Hour: An FBI Thriller (FBI Thriller (...,Catherine Coulter,2004,Jove Books,http://images.amazon.com/images/P/0515135739.0...,http://images.amazon.com/images/P/0515135739.0...,http://images.amazon.com/images/P/0515135739.0...
49698,256407,0515135739,0,Eleventh Hour: An FBI Thriller (FBI Thriller (...,Catherine Coulter,2004,Jove Books,http://images.amazon.com/images/P/0515135739.0...,http://images.amazon.com/images/P/0515135739.0...,http://images.amazon.com/images/P/0515135739.0...
49699,262399,0515135739,0,Eleventh Hour: An FBI Thriller (FBI Thriller (...,Catherine Coulter,2004,Jove Books,http://images.amazon.com/images/P/0515135739.0...,http://images.amazon.com/images/P/0515135739.0...,http://images.amazon.com/images/P/0515135739.0...

In [55]:
# getting the matrix of which user rated which movies
rating_matrix = df.pivot(index="Book-Title", columns="User-ID", values="Book-Rating")
rating_matrix = rating_matrix.fillna(0)
rating_matrix

User-ID,254,507,882,1424,1435,1733,1903,2033,2110,2276,...,274808,275020,275970,276680,277427,277478,277639,278137,278188,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Beautiful Mind: The Life of Mathematical Genius and Nobel Laureate John Nash,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Without Remorse,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [56]:
# similarity scores between the books according to the cosine similarity
sim_matrix = pd.DataFrame(cosine_similarity(rating_matrix))
sim_matrix

,0,1,2,3,4,5,6,7,8,9,...,584,585,586,587,588,589,590,591,592,593
0,1.000000,0.054362,0.000000,0.000000,0.000000,0.000000,0.059426,0.078183,0.032848,0.065986,...,0.000000,0.114646,0.023432,0.000000,0.033829,0.000000,0.082740,0.000000,0.076540,0.000000
1,0.054362,1.000000,0.156642,0.000000,0.000000,0.013566,0.067089,0.100033,0.017154,0.043777,...,0.021520,0.134952,0.095175,0.071366,0.065405,0.083467,0.050517,0.119077,0.033117,0.200237
2,0.000000,0.156642,1.000000,0.000000,0.000000,0.069885,0.000000,0.172739,0.018296,0.053361,...,0.000000,0.093125,0.105377,0.151455,0.030776,0.000000,0.031694,0.174386,0.035321,0.036912
3,0.000000,0.000000,0.000000,1.000000,0.000000,0.084770,0.000000,0.000000,0.000000,0.000000,...,0.075640,0.000000,0.064675,0.082419,0.013523,0.000000,0.074854,0.054180,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.102862,...,0.065547,0.000000,0.027057,0.082808,0.000000,0.095336,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
589,0.000000,0.083467,0.000000,0.000000,0.095336,0.000000,0.039658,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.033756,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.152183
590,0.082740,0.050517,0.031694,0.074854,0.000000,0.050342,0.000000,0.146162,0.080765,0.061680,...,0.101069,0.000000,0.044037,0.033517,0.032792,0.000000,1.000000,0.000000,0.000000,0.000000
591,0.000000,0.119077,0.174386,0.054180,0.000000,0.029378,0.057205,0.000000,0.019503,0.074655,...,0.000000,0.027795,0.032461,0.057954,0.067433,0.000000,0.000000,1.000000,0.037650,0.115229
592,0.076540,0.033117,0.035321,0.000000,0.000000,0.000000,0.028901,0.000000,0.219032,0.000000,...,0.081049,0.069003,0.126934,0.086958,0.061157,0.000000,0.000000,0.037650,1.000000,0.037570
593,0.000000,0.200237,0.036912,0.000000,0.000000,0.000000,0.048928,0.000000,0.063944,0.063854,...,0.000000,0.027735,0.061185,0.057830,0.045206,0.152183,0.000000,0.115229,0.037570,1.000000

In [57]:
# function for the recommendation
def recommend(title, n):
    '''function that recommends n books similar to the book given'''
    # id of the books in the list 
    id_in_the_list = freq_read_books.index(title)
    
    # id of the books similar tp the given book
    id_of_the_similar_books = sim_matrix.loc[id_in_the_list,].sort_values(ascending=False)[1:(n+1)].index
    
    # list of recommended books
    recommended_books = [freq_read_books[x] for x in id_of_the_similar_books]

    # informations about the books
    info = booksDf.loc[booksDf["Book-Title"].isin(recommended_books),].drop(["Image-URL-S", "Image-URL-M"], axis=1)

    return info


recommend('1984', 3)

,Book-Title,ISBN,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
162545,Slaughterhouse Five or the Children's Crusade:...,0440180295,Kurt Vonnegut,1991,Laurel,http://images.amazon.com/images/P/0440180295.0...
179417,The Bonesetter's Daughter,0399146431,Amy Tan,2001,Putnam Publishing Group,http://images.amazon.com/images/P/0399146431.0...
191599,The Handmaid's Tale,0449212602,Margaret Atwood,1989,Fawcett Books,http://images.amazon.com/images/P/0449212602.0...

In [58]:
import pickle

# saving the freqquently read books
with open('./pickleFiles/freqBooks.pkl', 'wb') as file:
    pickle.dump(freq_read_books, file)

# saving the similarity matrix
sim_matrix.to_csv('./Datasets/sim_matrix.csv')